# Site settings
title: "nadya"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
url: "https://nadya.ramottamado.dev"
description: > # this means to ignore newlines until "baseurl:"
  Nadya Jekyll theme.<br />
  Made with ❤️.
logo: "favicon.svg"
icon: "favicon.ico"
permalink: /:title/
excerpt_separator: <!--more-->
nav_pages:
  - categories.html
  - about.md

sitemap:
  changefreq: monthly

fb_page: 103250301049786
fb_author: 100000091609630
gravatar_author: "https://www.gravatar.com/avatar/90b290098c6a408c075ab0fd3b1f5783?s=300"
linkedin_username: ramottamado
github_username: ramottamado
twitter_username: theramottamado
ig_username: theramottamado
fb_username: theramottamado

google_site_verification: "zaJj36ddah20RkBG1RrQqWm-IlXepNuw8ch6SYXeBPQ"

fb_article: true
disable_social: true

feed:
  excerpts_only: true

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html

remote_theme: ramottamado/nadya@v0.1.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme
