# Site settings
title: "nadya"
email: "hello@ramottamado.dev"
author:
  name: "Tamado Ramot Sitohang"
  twitter: "theramottamado"
  url: "https://ramottamado.dev"
description: >- # this means to ignore newlines and trim last newline
  Nadya Jekyll theme.<br />
  Made with ❤️.

# Layout
nav_pages:
  - categories.html
  - about.md

# Logo
logo: "favicon.svg"
icon: "favicon.ico"

# Social
disable_social: true

# SEO
webmaster_verifications:
  google: "zaJj36ddah20RkBG1RrQqWm-IlXepNuw8ch6SYXeBPQ"
github:
  username: "ramottamado"
# instagram:
#   username: ""
# linkedin:
#   username: "ramottamado"
twitter:
  card: summary
  username: "theramottamado"
facebook:
  publisher: 103250301049786
  admins: 100000091609630
social:
  name: "Tamado Ramot Sitohang"
  links:
    - "https://ramottamado.dev"
    - "https://twitter.com/theramottamado"

# Plugin
sitemap:
  changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html

remote_theme: ramottamado/nadya@036c87f5

plugins:
  - jekyll-feed
  - jekyll-remote-theme
