# Site settings
title: "nadya"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
# url: ""
description: >- # this means to ignore newlines and trim last newline
  Nadya Jekyll theme.<br />
  Made with ❤️.

# Layout
# nav_pages:
#   - categories.html
#   - about.md

# Logo
# logo: "favicon.svg"
# icon: "favicon.ico"

# Social
# disable_social: true
# fb_article: true
# fb_page: ""
# fb_author: ""
# gravatar_author: ""
# linkedin_username: ""
# github_username: ""
# twitter_username: ""
# ig_username: ""
# fb_username: ""

# SEO
# google_site_verification: ""

# Plugin
# sitemap:
#   changefreq: monthly
# feed:
#   excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html
