# Site settings
title: "nadya"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
description: >- # this means to ignore newlines and trim last newline
  Nadya Jekyll theme.<br />
  Made with ❤️.

# Theme
nadya:
  date_format: "%b %d, %Y"

# Default
defaults:
  - scope:
      path: "_posts"
    values:
      image: /favicon.svg
      twitter:
        card: summary_large_image

# Layout
nav_pages:
  - categories.html
  - about.md

# Logo
logo: "favicon.svg"
# icon: "favicon.ico"

# Social
disable_social: true

# SEO
# google_site_verification: ""
# gravatar: ""
github:
  # username: ""
instagram:
  # username: ""
linkedin:
  # username: ""
twitter:
  card: summary
  # username: ""
facebook:
  # publisher: ""
  # author: ""
  # username: ""
social:
  # name: "Tamado Ramot Sitohang"
  # links:
  #   - "https://ramottamado.dev"

# Plugin Settings
# sitemap:
#   changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html

# Included Plugins
plugins:
  - jekyll-feed
