# Site settings
title: "nadya"
email: "tamado@tamado.codes"
author: "Tamado Ramot Sitohang"
description: >- # this means to ignore newlines and trim last newline
  Jekyll theme.
  Made with ❤️.

# Theme
nadya:
  date_format: "%b %d, %Y"
  attribution: true
  social: true

# Giscus
giscus:
  repo: "ramottamado/nadya"
  repo_id: "R_kgDOGxYEvA"
  category: "Announcements"
  category_id: "DIC_kwDOGxYEvM4CBNDK"
  mapping: "og:title"
  reactions: 0
  input: "top"

# Default
# defaults:
#   - scope:
#       path: "_posts"
#     values:
#       twitter:
#         card: summary_large_image

# Layout
# nav_pages:
#   - categories.md
#   - about.md

# Logo
favicon: "favicon.svg"
logo: "favicon.svg"
icon: "favicon.png"
alt_icon: "favicon.ico"

# SEO
# google_site_verification: ""
# gravatar: ""
github:
  username: "ramottamado"
instagram:
  # username: ""
linkedin:
  # username: ""
twitter:
  card: summary
  username: "github"
facebook:
  # publisher: ""
  # author: ""
  # username: ""
social:
  # name: "Tamado Ramot Sitohang"
  # links:
  #   - "https://tamado.codes"

# Plugin Settings
# sitemap:
#   changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:title

# Build settings
markdown: kramdown
# kramdown:
#   syntax_highlighter_opts:
#     default_lang: html

# Included Plugins
plugins:
  - jekyll-feed
