# Site settings
title: "nadya"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
url: "https://nadya.ramottamado.dev"
description: >- # this means to ignore newlines and trim last newline
  Jekyll theme.
  Made with ❤️.

nadya:
  disable_social: true
#   disable_attribution: true

# Layout
nav_pages:
  - categories.md
  - about.md

# Logo
favicon: "favicon.svg"
logo: "favicon.svg"
alt_icon: "favicon.ico"
icon: "favicon.png"

# SEO
google_site_verification: "zaJj36ddah20RkBG1RrQqWm-IlXepNuw8ch6SYXeBPQ"
github:
  username: "ramottamado"
twitter:
  card: summary
  username: "theramottamado"
facebook:
  publisher: 103250301049786
  author: 100000091609630
social:
  name: "Tamado Ramot Sitohang"
  links:
    - "https://ramottamado.dev"
    - "https://twitter.com/theramottamado"

# Plugin
sitemap:
  changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html

remote_theme: ramottamado/nadya

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jemoji
