# Site settings
title: "nadya"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
# tagline: ""
description: >- # this means to ignore newlines and trim last newline
  Nadya Jekyll theme.<br />
  Made with ❤️.

# Theme
nadya:
  date_format: "%b %d, %Y"
  disable_attribution: false
  disable_social: true

# Default
# defaults:
#   - scope:
#       path: "_posts"
#     values:
#       twitter:
#         card: summary_large_image

# Layout
# nav_pages:
#   - categories.md
#   - about.md

# Logo
favicon: "favicon.svg"
logo: "favicon.svg"
icon: "favicon.png"
alt_icon: "favicon.ico"

# SEO
# google_site_verification: ""
# gravatar: ""
github:
  # username: ""
instagram:
  # username: ""
linkedin:
  # username: ""
twitter:
  card: summary
  # username: ""
facebook:
  # publisher: ""
  # author: ""
  # username: ""
social:
  # name: "Tamado Ramot Sitohang"
  # links:
  #   - "https://ramottamado.dev"

# Plugin Settings
# sitemap:
#   changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html

# Included Plugins
plugins:
  - jekyll-feed
